# Generated by Django 5.0.6 on 2024-05-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.AutoField(db_column='ActorId', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=35, null=True)),
            ],
            options={
                'db_table': 'Actor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(db_column='MovieID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=70)),
                ('year', models.IntegerField(db_column='Year', null=True)),
                ('score', models.FloatField(db_column='Score', null=True)),
                ('votes', models.IntegerField(db_column='Votes', null=True)),
            ],
            options={
                'db_table': 'Movie',
                'managed': False,
            },
        ),
    ]
