# Generated by Django 5.0.6 on 2024-05-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('year', models.IntegerField()),
                ('score', models.FloatField()),
                ('votes', models.IntegerField()),
            ],
            options={
                'db_table': 'Movie',
                'managed': False,
            },
        ),
    ]
