# Generated by Django 5.0.6 on 2024-05-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas_pweb2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='MovieID', max_length=35, null=True)),
            ],
        ),
    ]
