# Generated by Django 5.0.6 on 2024-05-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas_pweb2', '0002_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.IntegerField(db_column='ActorId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(db_column='Name', max_length=35, null=True),
        ),
    ]
