# Generated by Django 5.0.6 on 2024-05-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas_pweb2', '0002_casting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Casting',
        ),
    ]
