# Generated by Django 5.0.6 on 2024-05-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas_pweb2', '0003_alter_actor_actor_id_alter_actor_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'managed': False},
        ),
    ]
