# Generated by Django 5.0.6 on 2024-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas_pweb2', '0004_alter_actor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(db_column='MovieID')),
                ('actor_id', models.IntegerField(db_column='ActorId')),
                ('ordinal', models.IntegerField(blank=True, db_column='Ordinal', null=True)),
            ],
            options={
                'db_table': 'Casting',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='actor',
            table='Actor',
        ),
    ]
