# Generated by Django 5.0.6 on 2024-05-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas_pweb2', '0005_casting_alter_actor_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casting',
            options={},
        ),
    ]
