# Generated by Django 5.0.6 on 2024-05-26 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas_pweb2', '0006_alter_casting_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='casting',
            unique_together={('movie', 'actor', 'ordinal')},
        ),
        migrations.AddField(
            model_name='casting',
            name='actor',
            field=models.ForeignKey(db_column='ActorId', default=1, on_delete=django.db.models.deletion.CASCADE, to='consultas_pweb2.actor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casting',
            name='movie',
            field=models.ForeignKey(db_column='MovieID', default=1, on_delete=django.db.models.deletion.CASCADE, to='consultas_pweb2.movie'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='casting',
            name='actor_id',
        ),
        migrations.RemoveField(
            model_name='casting',
            name='movie_id',
        ),
    ]
